### ISSUE TITLE
能否增加手工添加socks出站

### ISSUE THREAD

**Issue by bluaze** [twotreesus/V2RayPi#15]
在代理协议非vmess的情况下，v2ray.funpi也能发挥透明网关的作用

**Comment by twotreesus** [comment]
可以啊，具体是什么协议，Star到1k就加 😆，开玩笑。
有订阅链接吗，我空了调试一下。

**Comment by bluaze** [comment]
不好意思，我前面说的不太清楚
我并非说直接支持非vmess协议，虽然v2ray-core支持的代理协议还挺多的，但也并不是所有协议都支持，而且本项目也说过聚焦vmess协议，并不打算全协议支持
我上面所说是建议个取巧的办法，不管何代理协议，使用的代理客户端一般都会提供socks代理，这样，如果v2ray.funpi能添加socks出站的话，就能连接这些客户端使用相应的代理协议，从而达到代理协议自由

**Comment by twotreeszf** [comment]
可以考虑，哈哈，把手工填入的出站json作为一个高级节点，哈哈。具体需求细节可以在群里讨论一下。
